# Generated by Django 3.2.9 on 2021-12-04 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalVaksin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField()),
                ('kuota', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=128)),
                ('no_ktp', models.CharField(max_length=32)),
                ('no_wa', models.CharField(max_length=16)),
                ('bpjs', models.CharField(max_length=32)),
                ('alamat', models.CharField(max_length=512)),
                ('jml_vaksin', models.PositiveIntegerField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nama',),
            },
        ),
        migrations.CreateModel(
            name='RumahSakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=64)),
                ('nama', models.CharField(max_length=256)),
                ('alamat', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ReservasiVaksin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=32)),
                ('vaksin_ke', models.SmallIntegerField(max_length=3)),
                ('selesai', models.BooleanField(default=False)),
                ('jadwal_vaksin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jadwalvaksin')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pasien')),
            ],
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nama',),
            },
        ),
        migrations.AddField(
            model_name='jadwalvaksin',
            name='rumah_sakit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rumahsakit'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nama',),
            },
        ),
    ]
