# Generated by Django 3.2.9 on 2021-12-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211204_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalDokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=64)),
                ('nama', models.CharField(max_length=256)),
                ('spesialis', models.CharField(max_length=512)),
                ('jadwal', models.CharField(max_length=512)),
            ],
        ),
        migrations.RemoveField(
            model_name='petugas',
            name='rumah_sakit',
        ),
        migrations.AddField(
            model_name='rumahsakit',
            name='petugas',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rumah_sakit', to='app.petugas'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='jml_vaksin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AppointmentDokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=64)),
                ('keluhan', models.CharField(max_length=256)),
                ('jadwal_dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jadwaldokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pasien')),
            ],
        ),
    ]
