# Generated by Django 3.2.9 on 2021-12-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211206_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasivaksin',
            name='vaksin_ke',
            field=models.SmallIntegerField(default=0),
        ),
    ]
