# Generated by Django 3.2.9 on 2021-12-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_reservasivaksin_kode'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumahsakit',
            name='kecamatan',
            field=models.CharField(default='Beji', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rumahsakit',
            name='kodepos',
            field=models.CharField(default='16424', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rumahsakit',
            name='kota',
            field=models.CharField(default='Depok', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rumahsakit',
            name='provinsi',
            field=models.CharField(default='Jawa Barat', max_length=256, null=True),
        ),
    ]
