# Generated by Django 3.2.9 on 2021-12-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211207_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservasivaksin',
            name='selesai',
        ),
        migrations.AddField(
            model_name='reservasivaksin',
            name='status',
            field=models.CharField(choices=[('SELESAI', 'Selesai'), ('TERDAFTAR', 'Terdaftar'), ('GAGAL', 'Gagal')], default='GAGAL', max_length=32),
        ),
    ]
