# Generated by Django 3.2.9 on 2021-12-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211207_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwalvaksin',
            name='tanggal',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='waktu',
            field=models.TimeField(null=True),
        ),
    ]
