# Generated by Django 3.2.9 on 2021-12-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211207_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasivaksin',
            name='status',
            field=models.CharField(choices=[('SELESAI', 'Selesai'), ('TERDAFTAR', 'Terdaftar'), ('BATAL', 'Batal')], default='BATAL', max_length=32),
        ),
    ]
