# Generated by Django 3.1.1 on 2021-12-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211208_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdokter',
            name='kode',
        ),
    ]
